<?php

return [
    'students_kpi' => [
        'requires_module' => 'students',
        'requires_status' => ['active', 'dormant'],
        'min_data' => 1,
        'component' => 'KpiCard',
        'priority' => 100,
        'data_key' => 'entities.students',
    ],
    'guardians_kpi' => [
        'requires_module' => 'guardians',
        'requires_status' => ['active', 'dormant'],
        'min_data' => 1,
        'component' => 'KpiCard',
        'priority' => 90,
        'data_key' => 'entities.guardians',
    ],
    'enrollments_kpi' => [
        'requires_module' => 'academic',
        'requires_status' => ['active', 'dormant'],
        'min_data' => 1,
        'component' => 'KpiCard',
        'priority' => 85,
        'data_key' => 'entities.student_curricula',
    ],
    'assessments_kpi' => [
        'requires_module' => 'assessments',
        'requires_status' => ['active', 'dormant'],
        'min_data' => 1,
        'component' => 'KpiCard',
        'priority' => 80,
        'data_key' => 'entities.scores',
    ],
    'population_distribution' => [
        'requires_module' => 'students',
        'requires_status' => ['active', 'dormant'],
        'min_data' => 1,
        'component' => 'DistributionChart',
        'priority' => 75,
        'data_key' => 'distributions.students_by_class_level',
    ],
    'score_entry_progress' => [
        'requires_module' => 'assessments',
        'requires_status' => ['active', 'dormant'],
        'min_data' => 1,
        'component' => 'ScoreEntryProgress',
        'priority' => 72,
        'data_key' => 'distributions.score_entry_by_section',
    ],
    'assessments_trend' => [
        'requires_module' => 'assessments',
        'requires_status' => ['active'],
        'min_data' => 10,
        'component' => 'TrendChart',
        'priority' => 70,
        'data_key' => 'modules.assessments.daily_counts_30d',
    ],
    'students_trend' => [
        'requires_module' => 'students',
        'requires_status' => ['active'],
        'min_data' => 10,
        'component' => 'TrendChart',
        'priority' => 68,
        'data_key' => 'modules.students.daily_counts_30d',
    ],
    'recent_activity_feed' => [
        'requires_module' => 'activity_log',
        'requires_status' => ['active', 'dormant'],
        'min_data' => 1,
        'component' => 'ActivityFeedWidget',
        'priority' => 65,
        'data_key' => 'recent_activities',
    ],
    'data_gaps_panel' => [
        'always_render_if_gaps_exist' => true,
        'requires_module' => null,
        'requires_status' => [],
        'min_data' => 0,
        'component' => 'DataGapsPanel',
        'priority' => 60,
        'data_key' => 'data_gaps',
    ],
];
