<?php

/*
 * §9 step 5b-i (R13) — THE TEMPLATE THE PLATFORM ISSUES, as a single-sheet CSV.
 *
 * IT WAS A THREE-SHEET WORKBOOK AND THIS FILE USED TO ASSERT THAT. §9 step 5b-iii shipped the
 * operator screen, whose upload accepts CSV only — because that is what the validator's `read()`
 * parses — so the button handed the operator an `.xlsx` and the upload on the SAME screen refused
 * it. The workbook's other two sheets did not vanish: "Columns" and "Notes" render on the screen from
 * the same constants, which is what OperatorScreenTest asserts.
 *
 * EVERY ASSERTION HERE READS THE GENERATED BYTES, not the export's arrays. A template is a document
 * handed to another organisation; what matters is what a reader opens.
 *
 * AND THE FILE IS PARSED BY THE REAL VALIDATOR, not by a CSV reader written for this test. That is
 * the assertion that makes the round trip real: the template is only a template if the thing that
 * reads the format accepts it.
 */

use App\Finance\Console\ImportOpeningBalances;
use App\Finance\Exports\OpeningBalanceImportTemplateExport;
use App\Finance\Services\OpeningBalanceFileValidator;
use App\Models\Permission;
use App\Models\Role;
use App\Models\School;
use App\Models\User;
use App\Support\Money;
use Database\Seeders\DatabaseSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Maatwebsite\Excel\Excel as ExcelFormat;
use Maatwebsite\Excel\Facades\Excel;
use Spatie\Permission\PermissionRegistrar;

uses(RefreshDatabase::class);

/** The template exactly as it leaves the app: rendered to CSV bytes. */
function obtCsv(): string
{
    return Excel::raw(new OpeningBalanceImportTemplateExport, ExcelFormat::CSV);
}

/** The template's lines, as an operator's spreadsheet would read them. */
function obtRows(): array
{
    $path = tempnam(sys_get_temp_dir(), 'obtpl').'.csv';
    file_put_contents($path, obtCsv());

    try {
        $rows = [];
        $handle = fopen($path, 'rb');
        while (($row = fgetcsv($handle)) !== false) {
            $rows[] = $row;
        }
        fclose($handle);

        return $rows;
    } finally {
        @unlink($path);
    }
}

/** A web-session user in $school holding EXACTLY $permissions (mirrors PaymentRecordGateTest). */
function obtGateUser(School $school, array $permissions): User
{
    $roleName = 'obtpl_'.substr(md5(implode(',', $permissions)), 0, 10);
    $role = Role::firstOrCreate(['name' => $roleName, 'guard_name' => 'web']);
    foreach ($permissions as $permission) {
        Permission::firstOrCreate(['name' => $permission, 'guard_name' => 'web']);
    }
    $role->syncPermissions($permissions);

    $user = User::factory()->create(['school_id' => $school->id]);
    $user->grantSchoolAccess($school, $roleName);
    $user->flushSchoolAccessCache();
    app(PermissionRegistrar::class)->forgetCachedPermissions();

    return $user;
}

// ── The document a reader opens ──────────────────────────────────────────────────────────────────

it('is ONE CSV, whose first line is the header the validator requires', function () {
    // No title row, no comment line, no blank lead-in. `read()` takes the FIRST line as the header
    // and counts every line after it; anything decorative here is a parse error, not a nicety.
    expect(obtRows()[0])->toBe(array_keys(ImportOpeningBalances::COLUMNS));
});

it('samples MORE THAN ONE ROW FOR ONE STUDENT, which is the only way to show the repeated total', function () {
    $rows = obtRows();
    $columns = array_flip($rows[0]);

    $byStudent = [];
    foreach (array_slice($rows, 1) as $row) {
        $byStudent[$row[$columns['admission_number']]][] = $row;
    }

    expect(count($byStudent))->toBeGreaterThanOrEqual(2, 'the sample must show more than one student');
    expect(max(array_map('count', $byStudent)))
        ->toBeGreaterThanOrEqual(2, 'at least one student must carry SEVERAL rows — one row per fee type is the format');
});

it('keeps the two decimals and the minus sign, which a numeric binder would delete', function () {
    // MEASURED, NOT ASSUMED, and the assumption it replaces was wrong: "a CSV carries text verbatim"
    // is false. Written through PhpSpreadsheet's own DefaultValueBinder, '120000.00' reaches the CSV
    // as '120000' and '-5000.00' as '-5000' — the decimals disappear from the one place the format is
    // demonstrated. The export's StringValueBinder is what makes that independent of
    // config/excel.php's value_binder setting.
    $rows = obtRows();
    $columns = array_flip($rows[0]);

    foreach (array_slice($rows, 1) as $row) {
        expect($row[$columns['balance']])->toMatch('/^-?\d+\.\d{2}$/')
            ->and($row[$columns['student_total_balance']])->toMatch('/^-?\d+\.\d{2}$/');
    }

    $balances = array_map(
        fn (array $row) => Money::fromNaira($row[$columns['balance']])->toKobo(),
        array_slice($rows, 1),
    );

    expect(min($balances))->toBeLessThan(0, 'no sampled balance is negative — the sample never shows a credit');
});

it('samples rows §1 L1 WOULD ACCEPT — one stated total per student, equal to the sum of their balances', function () {
    $rows = obtRows();
    $columns = array_flip($rows[0]);

    $byStudent = [];
    foreach (array_slice($rows, 1) as $row) {
        $byStudent[$row[$columns['admission_number']]][] = $row;
    }

    foreach ($byStudent as $admission => $studentRows) {
        $stated = array_unique(array_map(fn (array $r) => $r[$columns['student_total_balance']], $studentRows));

        expect($stated)->toHaveCount(1,
            "student [{$admission}] states more than one total across their rows — §2 requires the SAME figure on every row");

        $sum = Money::fromKobo(0);
        foreach ($studentRows as $row) {
            $sum = $sum->plus(Money::fromNaira($row[$columns['balance']]));
        }

        expect($sum->toKobo())->toBe(
            Money::fromNaira(reset($stated))->toKobo(),
            "student [{$admission}]: Σ of the sampled balances does not equal the sampled student_total_balance — the template ships a sample its own importer rejects",
        );
    }
});

it('leaves the OPTIONAL column blank in a sample row, which is the only way to show a blank is accepted', function () {
    $rows = obtRows();
    $index = array_flip($rows[0])['wcbs_bill_reference'];
    $values = array_map(fn (array $row) => $row[$index], array_slice($rows, 1));

    expect(in_array('', $values, true))->toBeTrue(
        'no sample row leaves the optional reference blank, so the template never shows that a blank is accepted');
});

// ── THE ROUND TRIP: the validator's own reader accepts the template ──────────────────────────────

it('THE ROUND TRIP — the real validator parses the template it was handed, with no findings about its shape', function () {
    // THE ASSERTION NEITHER 5b-i NOR 5b-iii HAD. Both had a step that produced a file and a step that
    // consumed one, and nothing that made them meet — so "the button downloads a file" and "the
    // upload accepts a file" were both green while the two files were different formats. This parses
    // the ACTUAL template bytes with the ACTUAL reader.
    $path = tempnam(sys_get_temp_dir(), 'obtpl').'.csv';
    file_put_contents($path, obtCsv());

    try {
        $read = app(OpeningBalanceFileValidator::class)->read($path);
    } finally {
        @unlink($path);
    }

    expect($read['blankLines'])->toBe(0)
        ->and($read['records'])->toHaveCount(count(OpeningBalanceImportTemplateExport::SAMPLE_ROWS));

    // Every required column is present and populated on the first sampled record, keyed by the name
    // the reader derived from the header row — which is the header the template wrote.
    foreach (ImportOpeningBalances::COLUMNS as $column => $meta) {
        expect($read['records'][0]['values'])->toHaveKey($column);

        if ($meta['required']) {
            expect(trim($read['records'][0]['values'][$column]))->not->toBe('');
        }
    }

    // The reader numbers data lines from 2, because the header is line 1 — the numbers an operator
    // sees in their spreadsheet and the numbers the findings quote are the same numbers.
    expect($read['records'][0]['line'])->toBe(2);
});

// ── The route ────────────────────────────────────────────────────────────────────────────────────

it('serves the template as a CSV to a holder of the MAKER ability', function () {
    $this->seed(DatabaseSeeder::class);
    $school = School::factory()->create();
    $user = obtGateUser($school, ['finance.access', 'finance.opening-balance.submit']);

    $response = $this->actingAs($user)->withSession(['school_id' => $school->id])
        ->get('/api/v1/finance/opening-balance-batches/import/template');

    $response->assertOk();

    // THE EXTENSION IS PART OF THE CONTRACT. The upload on the same screen accepts csv/txt, so a
    // button that hands out an .xlsx is a button that feeds a refusal.
    expect($response->headers->get('content-disposition'))
        ->toContain('opening-balance-import-template.csv')
        ->and($response->headers->get('content-disposition'))->not->toContain('.xlsx');
});

it('refuses a user without finance.opening-balance.submit', function () {
    $this->seed(DatabaseSeeder::class);
    $school = School::factory()->create();

    // finance.access alone reaches the module — this arm is what makes the template's own ability
    // load-bearing rather than decorative. The checker's ability is included deliberately: the person
    // who APPROVES a batch is not thereby the person who uploads one, and neither of them is admitted
    // by the group gate alone.
    $user = obtGateUser($school, ['finance.access', 'finance.opening-balance.approve']);

    $this->actingAs($user)->withSession(['school_id' => $school->id])
        ->get('/api/v1/finance/opening-balance-batches/import/template')
        ->assertForbidden();
});
